pipeline {

    agent any

    environment {
        APP_NAME = 'devops-production-app'
        AWS_REGION = 'us-east-1'
        ECR_REPOSITORY = 'devops-production-app'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
	
        stage('Terraform Init') {
            steps {
                dir('terraform') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'jenkins-ecr-user']
                    ]) {
                        sh '''
                            terraform init
                        '''
                    }
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('terraform') {
                    sh '''
                        terraform validate
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'jenkins-ecr-user']
                    ]) {
                        sh '''
                            terraform plan
                        '''
                    }
                }
            }
        }

	 stage('Terraform Approval') {
            steps {
                input message: 'Terraform plan reviewed. Do you want to apply the infrastructure?', 
                      ok: 'Apply Terraform'
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: 'jenkins-ecr-user']
                    ]) {
                        sh '''
                            terraform apply -auto-approve
                        '''
                    }
                }
            }
        }

        stage('Application Test') {
            steps {
                dir('app') {
                    sh '''
                        npm ci
                        node --check server.js
                    '''
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('app') {
                    sh '''
                        docker build \
                          -t ${APP_NAME}:${BUILD_NUMBER} .
                    '''
                }
            }
        }

	stage('Trivy Security Scan') {
	   steps {
	        sh '''
			 trivy image \
			 --severity HIGH,CRITICAL \
			 ${APP_NAME}:${BUILD_NUMBER}
		 '''
		}
	}

        stage('Docker Test') {
            steps {
                sh '''
                    docker run -d \
                      --name ${APP_NAME}-test-${BUILD_NUMBER} \
                      -p 3100:3001 \
                      ${APP_NAME}:${BUILD_NUMBER}

                    sleep 5

                    curl -f http://localhost:3100/health

                    curl -f http://localhost:3100/api/products

                    docker rm -f ${APP_NAME}-test-${BUILD_NUMBER}
                '''
            }
        }

        stage('AWS Authentication') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: 'jenkins-ecr-user']
                ]) {
                    sh '''
                        echo "Checking AWS identity..."

                        aws sts get-caller-identity
                    '''
                }
            }
        }

        stage('ECR Login') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: 'jenkins-ecr-user']
                ]) {
                    sh '''
                        ACCOUNT_ID=$(aws sts get-caller-identity \
                          --query Account \
                          --output text)

                        echo "AWS Account: ${ACCOUNT_ID}"
                        echo "AWS Region: ${AWS_REGION}"

                        aws ecr get-login-password \
                          --region ${AWS_REGION} | \
                        docker login \
                          --username AWS \
                          --password-stdin \
                          ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                    '''
                }
            }
        }

        stage('Push to ECR') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: 'jenkins-ecr-user']
                ]) {
                    sh '''
                        ACCOUNT_ID=$(aws sts get-caller-identity \
                          --query Account \
                          --output text)

                        ECR_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}

                        echo "ECR Repository: ${ECR_URI}"

                        docker tag \
                          ${APP_NAME}:${BUILD_NUMBER} \
                          ${ECR_URI}:${BUILD_NUMBER}

                        docker tag \
                          ${APP_NAME}:${BUILD_NUMBER} \
                          ${ECR_URI}:latest

                        docker push ${ECR_URI}:${BUILD_NUMBER}

                        docker push ${ECR_URI}:latest
                    '''
                }
            }
        }
    }

    post {

        success {
            echo '=========================================='
            echo 'DevOps Production Platform CI/CD SUCCESS'
            echo 'Docker image pushed to Amazon ECR'
            echo '=========================================='
        }

        failure {
            echo '=========================================='
            echo 'CI/CD PIPELINE FAILED'
            echo 'Check the failed stage'
            echo '=========================================='
        }

        always {
            sh '''
                docker rm -f ${APP_NAME}-test-${BUILD_NUMBER} 2>/dev/null || true
            '''
        }
    }
}
